# Generated by Django 5.0.3 on 2024-03-19 15:01

import Management_Prestazioni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Management_Prestazioni.models.upload_to_prestazione, verbose_name='Referto')),
                ('note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Prestazione',
                'verbose_name_plural': 'Prestazioni',
            },
        ),
    ]
