# Generated by Django 5.0.2 on 2024-03-09 18:50

import Management_Prestazioni.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Management_Prestazioni.models.upload_to_prestazione, verbose_name='Referto')),
                ('note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_fornite', to=settings.AUTH_USER_MODEL, verbose_name='operatore')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_ricevute', to=settings.AUTH_USER_MODEL, verbose_name='paziente')),
            ],
            options={
                'verbose_name': 'Prestazione',
                'verbose_name_plural': 'Prestazioni',
            },
        ),
    ]
