# Generated by Django 5.0.2 on 2024-03-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_Prestazioni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestazione',
            name='operatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_fornite', to=settings.AUTH_USER_MODEL, verbose_name='operatore'),
        ),
        migrations.AlterField(
            model_name='prestazione',
            name='utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestazioni_ricevute', to=settings.AUTH_USER_MODEL, verbose_name='paziente'),
        ),
    ]
