# Generated by Django 5.0.3 on 2024-03-19 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management_Terapia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='prescrittore',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terapie_prescritte', to=settings.AUTH_USER_MODEL, verbose_name='prescrittore'),
        ),
        migrations.AddField(
            model_name='terapia',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terapie', to=settings.AUTH_USER_MODEL, verbose_name='paziente'),
        ),
    ]
