# Generated by Django 5.0.2 on 2024-03-07 11:16

import Management_Terapia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_Terapia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='utente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Management_Terapia.models.get_upload_path, verbose_name='Terapia'),
        ),
    ]
