# Generated by Django 5.0.2 on 2024-03-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='caregiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
