# Generated by Django 5.0.3 on 2024-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='private_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthcareuser',
            name='wallet_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
