# Generated by Django 5.0.2 on 2024-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_User', '0002_healthcareuser_caregiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcareuser',
            options={'ordering': ['nome', 'cognome', 'sesso', 'data_nascita'], 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
