# Generated by Django 5.0.2 on 2024-03-10 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_User', '0004_alter_healthcareuser_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareuser',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='healthcareuser',
            name='assistito',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver', to=settings.AUTH_USER_MODEL, verbose_name='Assistito'),
        ),
    ]
